[package]
name = "compute-shader"
version = "0.1.0"
authors = ["Andrea Cognolato <andrecogno@hotmail.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
glfw = "0.36.0"
rand = "0.7.3"
